services:
    Narmafzam\JalaliDateBundle\Model\Converter\DateConverter:
        arguments:
            - '@request_stack'

    Narmafzam\JalaliDateBundle\Twig\NarmafzamDateExtension:
        arguments:
            - '@Narmafzam\JalaliDateBundle\Model\Converter\DateConverter'
        tags:
            - { name: twig.extension }

    Narmafzam\JalaliDateBundle\Form\Type\NarmafzamJalaliDateType:
        arguments:
            - '@Narmafzam\JalaliDateBundle\Model\Converter\DateConverter'
            - '@request_stack'
        tags:
            - { name: form.type, alias: jSDateOld }

    Narmafzam\JalaliDateBundle\Form\Type\NarmafzamJalaliGregorianDateType:
        arguments:
            - '@Narmafzam\JalaliDateBundle\Model\Converter\DateConverter'
            - '@request_stack'
        tags:
            - { name: form.type, alias: jSDate }
